### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by piakchu** [menpo/lsfm#13]
Hi, @jabooth 

I use 25 face models(obj + texture file jpg) constructed by Photoscan, and then the code returns the following error message:

"LiuAng_open eyes_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [          ] 4% (1/25) - 00:09:54 remaining                     
Sunguizhou_open eyes_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [          ] 8% (2/25) - 00:09:12 remaining                     
Yangzhuosheng_open eyes_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=         ] 12% (3/25) - 00:08:41 remaining
bingguangtao_mianbu_zhengyan_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=         ] 16% (4/25) - 00:08:40 remaining
cuilixiang_mianbu_zhengyan_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [==        ] 20% (5/25) - 00:08:18 remaining 
guiwenlong_open eyes_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [==        ] 24% (6/25) - 00:07:56 remaining                    
gulailiang_open eyes_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [==        ] 28% (7/25) - 00:07:25 remaining                    
heming_mianbu_zhengyan_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [===       ] 32% (8/25) - 00:06:59 remaining                   
 jijun_open eyes_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [===       ] 36% (9/25) - 00:06:32 remaining                    
jiyang_mianbu_zhengyan_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [====      ] 40% (10/25) - 00:06:14 remaining 
linxiaofeng_mianbu_zhengyan_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [====      ] 44% (11/25) - 00:05:53 remaining                   
liyang_open eyes_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [====      ] 48% (12/25) - 00:05:28 remaining
liyuan_mianbu_zhengyan_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=====     ] 52% (13/25) - 00:05:06 remaining                  
luting_open eyes_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=====     ] 56% (14/25) - 00:04:41 remaining
pankexing_mianbu_zhengyan_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [======    ] 60% (15/25) - 00:04:15 remaining
qianzhiqiang_open eyes_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [======    ] 64% (16/25) - 00:03:50 remaining
sungongjian_lianbu_zhengyan_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [======    ] 68% (17/25) - 00:03:23 remaining  
sunxin_open eyes_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=======   ] 72% (18/25) - 00:02:57 remaining
wangjianguo_mianbu_zhengyan_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=======   ] 76% (19/25) - 00:02:32 remaining 
xingwei_mianbu_zhengyan_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [========  ] 80% (20/25) - 00:02:07 remaining
xuyuwen_mianbu_zhengyan_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [========  ] 84% (21/25) - 00:01:42 remaining
yanmengjie_open eyes_mod - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [========  ] 88% (22/25) - 00:01:15 remaining                  
Traceback (most recent call last):
  File "D:/研究生相关/LSFM/lsfm-master/bin/lsfm", line 285, in <module>
    main(docopt(__doc__))
  File "D:/研究生相关/LSFM/lsfm-master/bin/lsfm", line 269, in main
    correspond_and_save(r, id_, path, verbose=verbose)
  File "D:/研究生相关/LSFM/lsfm-master/bin/lsfm", line 76, in correspond_and_save
    mesh = lio.import_mesh(path)
  File "D:\研究生相关\LSFM\lsfm-master\lsfm\io.py", line 41, in import_mesh
    if mesh.texture.pixels.dtype != np.float64:
AttributeError: 'TriMesh' object has no attribute 'texture'
"

The obj files have no problem, I can view them in MeshLab, so I don't know why all of them failed. Would you please give me some help.
Thanks.

**Comment by patricksnape** [comment]
Can you show an example of one of the textures? The face detection is failing

**Comment by wenpanli** [comment]
Hi， I met the problem same with you, do you have solved this problem?

**Comment by patricksnape** [comment]
Can you show an example of one of the textures? The face detection is failing

**Comment by wenpanli** [comment]
> Can you show an example of one of the textures? The face detection is failing

Thanks for your reply. I have figured out this problem. I find that my ply files do not have geometrical information, it works after they are converted to obj files.
However, I met another problem: it needs to download the "balanced_frontal_face_aam_v0_py3.pkl" from website:static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl in  DENSE CORRESPONDENCE, which always fails and shows the following message：

Downloading balanced_frontal_face_aam fitter
http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl /home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/menpofit/data/balanced_frontal_face_aam_v0_py3.pkl
001 - FAILED TO CORRESPOND: <urlopen error [Errno 110] Connection timed out>
Correspondence: [==        ] 25% (1/4) - 00:06:58 remaining                     Downloading balanced_frontal_face_aam fitter
http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl /home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/menpofit/data/balanced_frontal_face_aam_v0_py3.pkl
^A002 - FAILED TO CORRESPOND: <urlopen error [Errno 110] Connection timed out>
Correspondence: [=====     ] 50% (2/4) - 00:04:32 remaining                     Downloading balanced_frontal_face_aam fitter
http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl /home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/menpofit/data/balanced_frontal_face_aam_v0_py3.pkl
003 - FAILED TO CORRESPOND: <urlopen error [Errno 110] Connection timed out>
Correspondence: [=======   ] 75% (3/4) - 00:02:14 remaining                     Downloading balanced_frontal_face_aam fitter
http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl /home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/menpofit/data/balanced_frontal_face_aam_v0_py3.pkl
004 - FAILED TO CORRESPOND: <urlopen error [Errno 110] Connection timed out>
Correspondence: [==========] 100% (4/4) - done.     
  
and then in  "INITIAL PCA + PRUNE", it goes wrong and shows the following message:

****** 1. INITIAL PCA + PRUNE **********

Traceback (most recent call last):
  File "/home/anna/anaconda2/envs/lsfm/bin/lsfm", line 285, in <module>
    main(docopt(__doc__))
  File "/home/anna/anaconda2/envs/lsfm/bin/lsfm", line 281, in main
    pca_and_prune(r, verbose=verbose)
  File "/home/anna/anaconda2/envs/lsfm/bin/lsfm", line 100, in pca_and_prune
    verbose=True)
  File "/home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/lsfm/model.py", line 14, in pca_and_weights
    model = PCAModel(meshes, verbose=verbose)
  File "/home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/menpo/model/pca.py", line 1199, in __init__
    return_template=True, verbose=verbose)
  File "/home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/menpo/math/linalg.py", line 125, in as_matrix
    template = vectorizables[0]
  File "/home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/menpo/base.py", line 482, in __getitem__
    return self._callables[slice_]()
IndexError: list index out of range

I am looking for a solution. Thanks in advance.

**Comment by shubhamag** [comment]
+1, facing the same issue as @SampanLee  in PCA+Pruen stage : 
 
****** 1. DENSE CORRESPONDENCE **********

Downloading balanced_frontal_face_aam fitter
http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl /home/shubham/anaconda3/envs/lsfm2/lib/python3.5/site-packages/menpofit/data/balanced_frontal_face_aam_v0_py3.pkl
Jim - FAILED TO CORRESPOND: <urlopen error [Errno 110] Connection timed out>

****** 1. INITIAL PCA + PRUNE **********
return self._callables\[slice_\]()
IndexError: list index out of range

**Comment by patricksnape** [comment]
@jabooth I think these files were on the old share and were being forwarded? Do you have this model somewhere we can host on github?

**Comment by baymin182** [comment]
do you have the key file "balanced_frontal_face_aam_v0_py3.pkl"? can you share it to me? my mail is bayminbx@tju.edu.cn

**Comment by patricksnape** [comment]
@nontas Do you have it?

**Comment by jabooth** [comment]
@patricksnape @shubhamag @nontas the issue with the static host should be resolved now, file should be downloadable here again:

http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl

Would be great to not have this on a server which needs ongoing maintenance though.

**Comment by weihualiuhupituzi** [comment]
> @patricksnape @shubhamag @nontas the issue with the static host should be resolved now, file should be downloadable here again:
> 
> http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl
> 
> Would be great to not have this on a server which needs ongoing maintenance though.

Hi, jabooth, 
I also met the problem that show here:
AttributeError: 'TriMesh' object has no attribute 'texture'
so I had download the data balanced_frontal_face_aam_v0_py3.pkl successfully, but where should I put the file in? 
I have try the root follow:
/home/weihua/annaconda_weihua/envs/lsfm/lib/python3.5/site-packages/lsfm/data/balanced_frontal_face_aam_v0_py3.pkl'
but it does not work, it still  report the same error.

**Comment by xuchang468** [comment]
> > 您可以显示其中一种纹理的示例吗？人脸检测失败
> 
> 感谢您的回复。我已经解决了这个问题。我发现我的层文件没有几何信息，将它们转换为obj文件后可以使用。
> 但是，我遇到了另一个问题：它需要在DENSE CORRESPOND上从网站：static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl下载“ balanced_frontal_face_aam_v0_py3.pkl”，该消息始终失败并显示以下消息：
> 
> 下载balanced_frontal_face_aam钳工
> http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl /home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/menpofit/data/balanced_frontal_face_aam_v0_py3.pkl
> 001 -失败对应：<urlopen错误[Errno 110]连接超时>
> 对应：[==] 25％（1/4）-剩余00:06:58正在下载balanced_frontal_face_aam钳工
> [http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3。 PKL](http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl) /home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/menpofit/data/balanced_frontal_face_aam_v0_py3.pkl
> ^ A002 -无法对应：<的urlopen错误[错误110]连接超时>
> 对应：[=====]剩余50％（2/4）-00:04:32正在下载balanced_frontal_face_aam钳工
> http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl / home / anna / anaconda2 / envs / lsfm / lib / python3.5 / site-packages / menpofit / data / balanced_frontal_face_aam_v0_py3.pkl 003-
> 失败：<urlopen错误[Errno 110]连接超时>
> 对应：[=======] 75％（ 3/4）-剩余00:02:14正在下载balanced_frontal_face_aam钳工
> http://static.menpo.org/menpofit/balanced_frontal_face_aam_v0_py3.pkl /home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/ menpofit /数据/balanced_frontal_face_aam_v0_py3.pkl
> 004-失败：<urlopen错误[Errno 110]连接超时>
> 信件：[==========] 100％（4/4）-完成。
> 
> 然后在“ INITIAL PCA + PRUNE”中出错，并显示以下消息：
> 
> ****** 1.初始PCA +修剪**********
> 
> 追溯（最近一次通话最近）：
> 文件“ / home / anna / anaconda2 / envs / lsfm / bin / lsfm”，第285行，位于
> main（docopt（**doc**））
> 文件“ / home / anna / anaconda2 / envs / lsfm / bin / lsfm“，第281行，位于主
> pca_and_prune（r，详细=详细）
> 文件” / home / anna / anaconda2 / envs / lsfm / bin / lsfm“，第100行，位于pca_and_prune
> verbose = True）
> 文件” / home / anna / anaconda2 / envs / lsfm / lib / python3.5 / site-packages / lsfm / model.py“，第14行，在pca_and_weights
> 模型中= PCAModel（meshes，verbose = verbose）
> 文件” / home / anna / anaconda2 / envs /lsfm/lib/python3.5/site-packages/menpo/model/pca.py“，第1199行，**init**
> return_template = True，详细=详细）
> as_matrix
> 模板中的文件“ /home/anna/anaconda2/envs/lsfm/lib/python3.5/site-packages/menpo/math/linalg.py”第125行= vectorizables [0]
> 文件“ / home / anna / anaconda2 / envs / lsfm / lib / python3.5 / site-packages / menpo / base.py“，第482行，在**getitem**
> 返回self._callables slice_
> IndexError：列表索引超出范围
> 
> 我正在寻找解决方案。提前致谢。

Hello, can you provide me with some data in obj format, my email is schizopeplum@gmail.com, for which I would be very grateful.

**Comment by patricksnape** [comment]
Sorry I'm unsure about what you would like here?

**Comment by xuchang468** [comment]
> Sorry I'm unsure about what you would like here?

I use some face models(obj + jpg+mtl) , but the code returns the following error message:
(lsfm) C:\Users\admin>lsfm -i C:\Users\admin\Desktop\lsfm-master\sjrl -o C:\Users\admin\Desktop\lsfm-master\output
Input directory provided - scanning for importable meshes
Found 1 input meshes under: C:\Users\admin\Desktop\lsfm-master\sjrl
Outputting results to C:\Users\admin\Desktop\lsfm-master\output


****** 1. DENSE CORRESPONDENCE **********

C:\Users\admin\Anaconda3\envs\lsfm\lib\site-packages\menpo\image\base.py:2652: MenpoDeprecationWarning: This method is no longer supported and will be removed in a future version of Menpo. Use .pixels_with_channels_at_back instead.
  MenpoDeprecationWarning)
1 - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [==========] 100% (1/1) - done.


****** 1. INITIAL PCA + PRUNE **********

Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\envs\lsfm\Scripts\lsfm-script.py", line 284, in <module>
    main(docopt(__doc__))
  File "C:\Users\admin\Anaconda3\envs\lsfm\Scripts\lsfm-script.py", line 280, in main
    pca_and_prune(r, verbose=verbose)
  File "C:\Users\admin\Anaconda3\envs\lsfm\Scripts\lsfm-script.py", line 99, in pca_and_prune
    verbose=True)
  File "C:\Users\admin\Anaconda3\envs\lsfm\lib\site-packages\lsfm\model.py", line 14, in pca_and_weights
    model = PCAModel(meshes, verbose=verbose)
  File "C:\Users\admin\Anaconda3\envs\lsfm\lib\site-packages\menpo\model\pca.py", line 1199, in __init__
    return_template=True, verbose=verbose)
  File "C:\Users\admin\Anaconda3\envs\lsfm\lib\site-packages\menpo\math\linalg.py", line 125, in as_matrix
    template = vectorizables[0]
  File "C:\Users\admin\Anaconda3\envs\lsfm\lib\site-packages\menpo\base.py", line 482, in __getitem__
    return self._callables[slice_]()
IndexError: list index out of range

So I want to know what went wrong and look forward to your reply.

**Comment by patricksnape** [comment]
Looks like face detection is failing? `Expected to find one face - found 0`

**Comment by xuchang468** [comment]
> Looks like face detection is failing? `Expected to find one face - found 0`

Yes, I saw this error, but the image format I used is completely correct, I don't know what went wrong.

**Comment by patricksnape** [comment]
The face detector failed? 🤷 

Try a different face detector maybe? It's really hard to debug without seeing the image.

**Comment by idesignitX** [comment]
Error loading fitter - purging damaged file: 002_neutral - FAILED TO CORRESPOND: 
You need to install the 'cyvlfeat' package in order to use this
functionality. We recommend that you use conda to achieve this -
try the command

    conda install cyvlfeat

in your terminal. Note that this package may be provided by another
channel such as the "menpo" channel or the "conda-forge" channel.
Failing that, try installing use pip:

    pip install cyvlfeat

Note that some packages (e.g. scikit-image) may have a different
name on pypi/conda than their import (skimage) and thus the above 
commands may fail.

**Comment by idesignitX** [comment]
E:\Miniconda3\envs\lsfm\lib\site-packages\menpo3d\rasterize\cpu.py:46: RuntimeWarning: divide by zero encountered in true_divide
  d = 1.0/(dot_jj * dot_kk - dot_jk * dot_jk)
E:\Miniconda3\envs\lsfm\lib\site-packages\menpo3d\rasterize\cpu.py:47: RuntimeWarning: invalid value encountered in multiply
  alpha = (dot_kk * dot_pj - dot_jk * dot_pk) * d
E:\Miniconda3\envs\lsfm\lib\site-packages\menpo3d\rasterize\cpu.py:48: RuntimeWarning: invalid value encountered in multiply
  beta = (dot_jj * dot_pk - dot_jk * dot_pj) * d
E:\Miniconda3\envs\lsfm\lib\site-packages\menpo3d\rasterize\cpu.py:66: RuntimeWarning: invalid value encountered in greater_equal
  alpha >= 0, beta >= 0),
E:\Miniconda3\envs\lsfm\lib\site-packages\menpo3d\rasterize\cpu.py:67: RuntimeWarning: invalid value encountered in less_equal
  alpha + beta <= 1)
E:\Miniconda3\envs\lsfm\lib\site-packages\menpo\image\base.py:2652: MenpoDeprecationWarning: This method is no longer supported and will be removed in a future version of Menpo. Use .pixels_with_channels_at_back instead.
  MenpoDeprecationWarning)
001_neutral - FAILED TO CORRESPOND: Expected to find one face - found 0
Correspondence: [=         ] 14% (1/7) - 00:02:58 remaining                     E:\Miniconda3\envs\lsfm\lib\site-packages\menpo3d\rasterize\cpu.py:58: RuntimeWarning: invalid value encountered in subtract
  c = 1 - a - b
002_neutral - FAILED TO CORRESPOND: Expected to find one face - found 0

**Comment by patricksnape** [comment]
Can you share an example mesh somehow so that we can try and debug? Face detection is failing.
