### ISSUE TITLE
AttributeError: 'TriMesh' object has no attribute 'texture'

### ISSUE THREAD

**Issue by GangHu1993** [menpo/lsfm#26]
/home/parallels/anaconda3/envs/lsfm/lib/python3.5/site-packages/menpo3d/io/input/mesh/base.py:53: UserWarning: texture was found, but no tcoords were recovered, reverting to an untextured mesh.
  warnings.warn('texture was found, but no tcoords were recovered, '
Traceback (most recent call last):
  File "/home/parallels/anaconda3/envs/lsfm/bin/lsfm", line 285, in <module>
    main(docopt(__doc__))
  File "/home/parallels/anaconda3/envs/lsfm/bin/lsfm", line 269, in main
    correspond_and_save(r, id_, path, verbose=verbose)
  File "/home/parallels/anaconda3/envs/lsfm/bin/lsfm", line 76, in correspond_and_save
    mesh = lio.import_mesh(path)
  File "/home/parallels/anaconda3/envs/lsfm/lib/python3.5/site-packages/lsfm/io.py", line 41, in import_mesh
    if mesh.texture.pixels.dtype != np.float64:
AttributeError: 'TriMesh' object has no attribute 'texture'

**Comment by LeeTaiTai** [comment]
@GangHu1993  hi, do you solve this question?

**Comment by RhythmJnh** [comment]
You should first open your model file in meshlab and observe if there is any texture. If so, change your texture image to the same name as the model file. If not, :(

**Comment by gaurav-1205** [comment]
Even I am facing the same problem!

**Comment by cvmaker93** [comment]
Hi，I also encountered the same problem. How did you solve it？
