### ISSUE TITLE
List index out of range Error

### ISSUE THREAD

**Issue by a78239636** [menpo/lsfm#40]
I want to deal with the wrl file and the jpg file in simpleIput1/ 
If you need jpg example please email a78239636@163.com(my email adress)

However, met this error list out of range, so anyone know about this ? 
Thanks.

----------------------This is  Full error description ---------------------------------------

~$ lsfm -o simpleOut3/  -i simpleInput1/
Input directory provided - scanning for importable meshes
Found 3 input meshes under: simpleInput1
Outputting results to /home/li_gang/simpleOut3

****** 1. DENSE CORRESPONDENCE **********
Correspondence: [==========] 100% (3/3) - done.                                 
****** 1. INITIAL PCA + PRUNE **********

Traceback (most recent call last):
  File "/usr/local/bin/lsfm", line 4, in <module>
    __import__('pkg_resources').run_script('lsfm==1.1.0rc1', 'lsfm')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/lsfm-1.1.0rc1-py3.5.egg/EGG-INFO/scripts/lsfm", line 285, in <module>
    main(docopt(__doc__))
  File "/usr/local/lib/python3.5/dist-packages/lsfm-1.1.0rc1-py3.5.egg/EGG-INFO/scripts/lsfm", line 281, in main
    pca_and_prune(r, verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/lsfm-1.1.0rc1-py3.5.egg/EGG-INFO/scripts/lsfm", line 100, in pca_and_prune
    verbose=True)
  File "/usr/local/lib/python3.5/dist-packages/lsfm-1.1.0rc1-py3.5.egg/lsfm/model.py", line 14, in pca_and_weights
    model = PCAModel(meshes, verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/menpo/model/pca.py", line 1199, in __init__
    return_template=True, verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/menpo/math/linalg.py", line 125, in as_matrix
    template = vectorizables[0]
  File "/usr/local/lib/python3.5/dist-packages/menpo/base.py", line 497, in __getitem__
    return self._callables[ slice_ ] ( )
IndexError: list index out of range

**Comment by a78239636** [comment]
Ok, I know why. In landmark and correspondece step, it will output some file. But If it first failed, it has created some dictories. The seconde time you try, when it find the dir, it will think get the correct output. Howere, there are nothing in dirs. So when it try to get file from output mkdir, will cause List index out of rang
